### ISSUE TITLE
Traduction manquante

### ISSUE THREAD

**Issue by Upd473** [pmspr4100/MA-XML-12-FRENCH#104]
- **Version MIUI:** 21.3.24
- **Nom de l'appareil:** Mi 10 Ultra 

**Capture d'écran/Description:**
Paramètres-> Écran d'accueil-> System navigation 
![Screenshot_2021-03-27-14-08-25-676_com miui home](https://user-images.githubusercontent.com/81473032/112721753-02886100-8f06-11eb-8e96-a086fda7b3d0.jpg)

**Comment by jblum66** [comment]
Merci. Ce sera corrigé dans 9bb34a4ad346141b0464ab60e248a4718760233f

**Comment by Upd473** [comment]
Merci à vous pour le travail abattu 👍
