### ISSUE TITLE
Traduction hors champ menu volume

### ISSUE THREAD

**Issue by xuorx** [pmspr4100/MA-XML-12-FRENCH#108]
Version MIUI: 21.4.21
Bonjour.
Je me permets de vous signaler que la traduction sort des cadres dans le menu volume de l'appareil.

Coulisser pour régler la minuterie
Coulisser pour régler la minuterie

De plus la minuterie est précisée deux fois ?

![Screenshot_2021-04-23-07-26-42-438_com microsoft emmx](https://user-images.githubusercontent.com/83055553/115822840-82babd00-a405-11eb-9070-d32b1148e27d.jpg)

**Comment by Micdu70** [comment]
> De plus la minuterie est précisée deux fois ?

Oui c'est normal car on ne peut pas faire deux messages différents...
