### ISSUE TITLE
Paramètre additionnel geste raccourci

### ISSUE THREAD

**Issue by xuorx** [pmspr4100/MA-XML-12-FRENCH#114]
Miui 21.4.21

Il manque plusieurs traduction dans le menu paramètre additionnel :
Capture d'écran ci dessous : 
![IMG_20210423_232630](https://user-images.githubusercontent.com/83055553/115931500-809b4180-a48b-11eb-802b-4efca2db9718.jpg)

1 : press and swipe horizontaly with a knuckle
appuyer et glisser horizontalement en secouant

2 : Draw V with a Knuckle
Dessiner un V en secouant le téléphone ?

BIS :
![IMG_20210423_233209](https://user-images.githubusercontent.com/83055553/115931834-251d8380-a48c-11eb-9b18-0a9ea54a575d.jpg)

1 : Draw V with a Knuckle
Dessiner un V en secouant le téléphone ?
2 : this gesture doesn't work near screen edge
Ce geste ne fonctionne pas avec les écrans incurvés ?

Il s'agit de proposition ne maîtrisant pas totalement.

**Comment by Micdu70** [comment]
Knuckle = L'articulation du doigt, pour toquer l'écran ou faire un dessin

J'ai aussi traduit pleins d'autres gestes. ;)
