### ISSUE TITLE
Utilisation des données

### ISSUE THREAD

**Issue by xuorx** [pmspr4100/MA-XML-12-FRENCH#119]
Miui 21.4.21
Dans les paramètres utilisation des données :
![IMG_20210424_140320](https://user-images.githubusercontent.com/83055553/115958067-12e02b80-a506-11eb-9827-3ff6e249a02e.jpg)
Définir l'utilisation des données - forfait des données sim 1 et 2
Monthly data limit
Définir la limite des données mensuelles ?

**Comment by Micdu70** [comment]
J'ai traduis par "Quota de données mensuelles" mais j'ai aussi changé le terme "cellulaire" par "mobile" dans 99% des cas.

"cellulaire" n'est pas un terme très utilisé en France. :)
