### ISSUE TITLE
traduction FR

### ISSUE THREAD

**Issue by MassimoBF** [pmspr4100/MA-XML-12-FRENCH#131]
- **Version MIUI:** 21.5.12
- **Nom de l'appareil:** Mi 11

Salut ,

Je reviens vers vous avec des petites correction: 

-----------------------------------------------------------------------
Dans les fonds d'ecan le " More " a traduire par '' Plus " 

![Inked184929218_456374698794263_874550226246677229_n_LI](https://user-images.githubusercontent.com/81257813/118551867-7b65a580-b75e-11eb-87c0-c78feb004e98.jpg)

------------------------------------------------------------------------
Paramètre  -> Retour d'information ->   "My feedback"   en " Mes rapports " ??
                                                          ->   " Get logs "   en " Journaux "  ?? 
![Inked184769546_320403959471560_8701039820326820438_n_LI](https://user-images.githubusercontent.com/81257813/118552372-24140500-b75f-11eb-832d-1e4293c592e9.jpg)

Dans Get logs il y a également un mots ou une phrase en chinois :  
![Inked186549629_208955294199097_2438561219825262522_n_LI](https://user-images.githubusercontent.com/81257813/118552509-5160b300-b75f-11eb-82a2-63de07ff22f8.jpg)

-------------------------------------------------------------------------

Paramètres  ->  Paramètres de localisation -> 

![Inked185295840_508927487131540_8552920197212368159_n_LI](https://user-images.githubusercontent.com/81257813/118552713-9389f480-b75f-11eb-9065-0465f403b9ac.jpg)

Merci a vous !

**Comment by Micdu70** [comment]
Salut ! :)

Concernant ton premier signalement, c'est normalement déjà résolu pour la prochaine ROM. J'ai aussi changé "Super wallpapers" en "Super fonds d'écran". ;)

Pour les autres signalements, je m'en occupe. 👍

**Comment by Micdu70** [comment]
Ah et concernant le message en chinois, j'ai simplement traduit par "Catégorie". ^^
