### ISSUE TITLE
Correction appel  21.5.20

### ISSUE THREAD

**Issue by MassimoBF** [pmspr4100/MA-XML-12-FRENCH#138]
- **Version MIUI:** 21.5.20
- **Nom de l'appareil:** Mi 11

Bonjour,

J'ai trouvé une nouvelle correction.

Lorsque que l'ont reçoit un appel ont peut répondre par " Repondre par un message" et ses messages ne sont pas traduit et donc s'envoient en anglais.

Voici la liste des correction dans l'ordre actuel ( image) 

- Je ne peux pas répondre. On se rappelle ?
- Je te rappelle tout de suite.
- Je t'appelle plus tard.
- Je ne peux pas répondre.  Ça va ?

SMS personnalisé est souvent écrit " Réponse personnalisée" chez les autres marque je sais pas si vous voulez le changer ou pas. 

![Inked185123388_1189827994793373_2398156609846064875_n_LI](https://user-images.githubusercontent.com/81257813/119183662-b294c900-ba74-11eb-964a-84bf29a59be5.jpg)

Merci d'avance!

**Comment by Micdu70** [comment]
Les traductions des réponses "toutes faites" par SMS existent déjà dans les apps systèmes 'TeleService.apk' et 'Telecom.apk' depuis quelques temps. :)

Sur mon Mi 9T en 21.5.20, ces phrases sont bien en français, comme sur la version précédente de la ROM. ;)

Concernant le "SMS personnalité" => "Réponse personnalisée", je suis d'accord pour changer cela.

**Comment by MassimoBF** [comment]
C'est bizarre en tout cas sur MI 11 ça ne l'est pas et je penses pas avoir vu d'option pour changer ça.
Merci quand meme.

**Comment by Micdu70** [comment]
Ce que je remarque, c'est que ton téléphone utilise les messages de l'appli "TeleService.apk":

```
./venus/TeleService.apk/res/values/strings.xml:1987:    <string name="respond_via_sms_canned_response_1">"Can't talk now. Call me later?"</string>
./venus/TeleService.apk/res/values/strings.xml:1988:    <string name="respond_via_sms_canned_response_2">"I'll call you right back."</string>
./venus/TeleService.apk/res/values/strings.xml:1989:    <string name="respond_via_sms_canned_response_3">"I'll call you later."</string>
./venus/TeleService.apk/res/values/strings.xml:1990:    <string name="respond_via_sms_canned_response_4">"Can't talk now. What's up?"</string>
```

Trad FR existante:

```
./French/main/TeleService.apk/res/values-fr/strings.xml:1724:    <string name="respond_via_sms_canned_response_1">Impossible de répondre maintenant. Pouvez-vous me rappeler plus tard ?</string>
./French/main/TeleService.apk/res/values-fr/strings.xml:1725:    <string name="respond_via_sms_canned_response_2">Je te rappelle tout de suite.</string>
./French/main/TeleService.apk/res/values-fr/strings.xml:1726:    <string name="respond_via_sms_canned_response_3">"Je t'appellerai plus tard."</string>
./French/main/TeleService.apk/res/values-fr/strings.xml:1727:    <string name="respond_via_sms_canned_response_4">Je ne peux pas parler. Quoi de neuf ?</string>
```

Alors que sur mon Mi 9T, ce sont les messages de l'appli "Telecom.apk":

```
./davinci/Telecom.apk/res/values/strings.xml:521:    <string name="respond_via_sms_canned_response_1">"Can't talk now. What's up?"</string>
./davinci/Telecom.apk/res/values/strings.xml:522:    <string name="respond_via_sms_canned_response_2">"I'll call you right back."</string>
./davinci/Telecom.apk/res/values/strings.xml:523:    <string name="respond_via_sms_canned_response_3">"I'll call you later."</string>
./davinci/Telecom.apk/res/values/strings.xml:524:    <string name="respond_via_sms_canned_response_4">"Can't talk now. Call me later?"</string>
```

Trad FR existante:

```
./French/main/Telecom.apk/res/values-fr/strings.xml:434:    <string name="respond_via_sms_canned_response_1">Impossible de parler maintenant. Quoi de neuf ?</string>
./French/main/Telecom.apk/res/values-fr/strings.xml:435:    <string name="respond_via_sms_canned_response_2">Je vous rappelle tout de suite.</string>
./French/main/Telecom.apk/res/values-fr/strings.xml:436:    <string name="respond_via_sms_canned_response_3">Je vous appellerai plus tard.</string>
./French/main/Telecom.apk/res/values-fr/strings.xml:437:    <string name="respond_via_sms_canned_response_4">Peux pas parler. On se rappelle ?</string>
```

Je comprends pas trop comment fonctionne tout cela mais ça m'a pas l'air très simple, merci Xiaomi. xD

**Comment by pmspr4100** [comment]
je vais appliquer une modification pour la prochaine version.

**Comment by Micdu70** [comment]
Est-ce que le problème est toujours présent dans la nouvelle ROM hebdomadaire (Weekly) @MassimoBF ?

**Comment by MassimoBF** [comment]
> Est-ce que le problème est toujours présent dans la nouvelle ROM hebdomadaire (Weekly) @MassimoBF ?

Salut , 
Non j'ai toujours les messages en anglais

**Comment by pmspr4100** [comment]
Lors de la mise à jour un wipe cache et préférable.

**Comment by jblum66** [comment]
Bonjour,
C'est toujours d'actualité @MassimoBF ?

**Comment by MassimoBF** [comment]
> Bonjour,
> C'est toujours d'actualité @MassimoBF ?

Bonjour oui c'est toujours comme ça.

**Comment by MassimoBF** [comment]
Bonjour depuis la dernière MAJ tout est ok . Merci !
