### ISSUE TITLE
Léger bug d'affichage

### ISSUE THREAD

**Issue by madvillain91** [pmspr4100/MA-XML-12-FRENCH#17]
- Version MIUI: 20.6.11
- Nom de l'appareil: Mi Note 10

Capture d'écran/Description:

Bonjour à toute l'équipe.
Hormis ce léger bug d'affichage je tenais à féliciter le travail de chacun sur ces traductions bravo tous, vous faites du super boulot.
Je ne sais pas si l'un d'entre vous est capable de remonter l'information sur le fait que le mail de confirmation du forum n'arrive jamais.
Je me suis proposé pour tenter de corriger le problème en écrivant à support@xiaomi.eu mais aucune réponse. Du coup c'est assez frustrant de ne pas pouvoir participer à 100% vis à vis de la communauté.
Merci de faire passer le mot si possible ;)
Mon adresse est mgfunk91@gmail.com.

![Screenshot_2020-06-15-23-15-11-780_com android quicksearchbox](https://user-images.githubusercontent.com/17130711/84707039-49503000-af5e-11ea-8b78-8d3714e37559.jpg)
![Screenshot_2020-06-15-23-15-08-434_com android quicksearchbox](https://user-images.githubusercontent.com/17130711/84707057-4f461100-af5e-11ea-8cf6-14df4dc7cd0c.jpg)
![Screenshot_2020-06-15-23-14-57-781_com android quicksearchbox](https://user-images.githubusercontent.com/17130711/84707072-5705b580-af5e-11ea-9c59-b00ef3a42f55.jpg)

**Comment by pmspr4100** [comment]
Salut pour les corrections cela ce passe ici, c'est moi qui ajoute les lignes manquante et corrige les oublies. Par contre sur les captures d'écrans je vois du Chinois donne moi le chemin pour arriver sur c'est options ou l'application.

**Comment by madvillain91** [comment]
![Screenshot_2020-06-16-15-52-25-824_com android settings](https://user-images.githubusercontent.com/17130711/84783445-8f060a80-afe9-11ea-80be-5ee5f4ca900f.jpg)
J'ai trouvé qu'en tapant le mot recherche dans la barre de recherche des paramètres du téléphone.
Sinon je fais glisser vers le haut depuis le bureau. Puis paramètres.

![Screenshot_2020-06-16-15-54-46-639_com android quicksearchbox](https://user-images.githubusercontent.com/17130711/84783583-b9f05e80-afe9-11ea-8f69-bd040b189869.jpg)

**Comment by pmspr4100** [comment]
Ok donc invalide.
Soit tu à mis à jour le lanceur Xiaomi via le Play Store ou autre.
Xiaomi.eu supprime toute trace de chinois de la ROM.

**Comment by madvillain91** [comment]
Impossible, il n'est même pas installer via le play store. Je ne passe que par la Rom xiaomi.eu 😕
![Screenshot_2020-06-17-09-44-48-160_com android vending](https://user-images.githubusercontent.com/17130711/84870323-73e5da00-b07f-11ea-86f2-9c8224f8caf0.jpg)

**Comment by madvillain91** [comment]
Ok, tu m'a mis sur une piste. Je pense avoir trouvé le soucis.
![Screenshot_2020-06-17-12-21-26-567_com miui securitycenter](https://user-images.githubusercontent.com/17130711/84886945-63405e80-b095-11ea-803a-9d0221696129.jpg)
![Screenshot_2020-06-17-12-16-01-776_com miui securitycenter](https://user-images.githubusercontent.com/17130711/84886955-66d3e580-b095-11ea-8fa7-aed7854d44e8.jpg)

**Comment by pmspr4100** [comment]
Ok donc pas la même version déinstalle si il te le propose
![Screenshot_2020-06-17-18-31-29-263_com miui securitycenter](https://user-images.githubusercontent.com/49132275/84924563-fe9ef700-b0c8-11ea-8c79-354828c309b0.jpg)
