### ISSUE TITLE
Navigateur encore de l'anglais

### ISSUE THREAD

**Issue by Ouaissss** [pmspr4100/MA-XML-12-FRENCH#175]
- **Version MIUI:** 12.5.6
- **Nom de l'appareil:** redmi note 10 pro

**Capture d'écran/Description:**
Et il y a aussi plusieurs choses dans le navigateur ( mi browser)
En faisant un appui long sur une adresse, le menu proposé est en anglais ( open in New tab, open in background tab, copy link url, Select text) 
Et pareil pour les images ( save image, view image, share image, set as wallpaper)
Et dans le menu profile ( en bas à droite du navigateur, il y a reduce data usage, exit,

Et aussi quand on ouvre un onglet en mode incognito, la page d'accueil est complètement en anglais ( you are incognito....)

Voili voilou

**Comment by Ouaissss** [comment]
Ps pendant qu'on y est il y a aussi dans le menu favoris historique, historique est écrit history

**Comment by jblum66** [comment]
Oui, l'application Mi Browser Global est en cours de traduction, car elle a été créée il y a quelques mois en repartant de zéro (l'ancienne appli était Mi Browser). J'ai commencé à traduire mais il reste des centaines de libellés encore.

**Comment by Ouaissss** [comment]
👍

**Comment by jblum66** [comment]
Progression : 59%
