### ISSUE TITLE
[20.6.18] Beaucoup de traductions manquantes

### ISSUE THREAD

**Issue by Micdu70** [pmspr4100/MA-XML-12-FRENCH#18]
- **Version MIUI:** 20.6.18
- **Nom de l'appareil:** Mi 9T

**Capture d'écran/Description:**
FR:
Beaucoup de traductions sont manquantes dans cette version 20.6.18 (phrases en anglais):
- Dans les réglages du téléphone (pour les menus "Portable hotspot"/"Wallpaper"/"Screen time"/"Mi Account")
- Quand on branche le port USB (écran pop-up tout en anglais)
- Peut être dans d'autres endroits..

=======================================================

EN:
Many missing translations in 20.6.18 version (english :
- In phone settings ("Portable hotspot"/"Wallpaper"/"Screen time"/"Mi Account" menus)
- When plug-in USB (pop-up screen is all in english)
- Maybe in others areas...

@ingbrzy Is it normal?

**Comment by pmspr4100** [comment]
Corrigé une erreur sur le Settings.apk

**Comment by Micdu70** [comment]
@pmspr4100 D'accord, merci pour ton retour. 👍
