### ISSUE TITLE
Icône calendrier jour en anglais

### ISSUE THREAD

**Issue by Ouaissss** [pmspr4100/MA-XML-12-FRENCH#180]
- **Version MIUI:** 12.5.8 stable
- **Nom de l'appareil:** redmi note 10 pro

**Capture d'écran/Description:**
Bonjour,
Je viens de voir que sur l'icône du calendrier, les jours sont en anglais (monday....)

**Comment by Micdu70** [comment]
Salut, 
Es-tu sûr de ne pas utiliser des icônes personnalisées ? Car ça peut venir de là. :)

**Comment by Ouaissss** [comment]
Non c'est le thème par défaut,
Il y a le jour en anglais et le chiffre en dessous.
L'application c'est bien le calendrier par défaut aussi

**Comment by Ouaissss** [comment]
Je viens de tenter, ça ne fonctionne pas mieux, sur l'icône du calendrier c'est écrit tue à la place de tuesday

**Comment by Micdu70** [comment]
Dans les paramètre du téléphone > Paramètres additionnels > Région, c'est bien sélectionné "France" ou autre ?

Si c'est "France" déjà, le problème vient surement du fait que la ROM Xiaomi.eu est basé sur une ROM "Globale" et pas "Chinoise"...

**Comment by pmspr4100** [comment]
> 
> 
>     * **Version MIUI:** 12.5.8 stable
> 
>     * **Nom de l'appareil:** redmi note 10 pro
> 
> 
> **Capture d'écran/Description:** Bonjour, Je viens de voir que sur l'icône du calendrier, les jours sont en anglais (monday....)

une capture d'écran STP

**Comment by mimik0** [comment]
Bonjour a tous, je me greffe j'ai le même problème 
Voir capture :
![IMG_20211109_224410](https://user-images.githubusercontent.com/59457838/141009843-f7319a23-0e27-45ac-ae17-b0e858d0e172.jpg)

**Comment by Ouaissss** [comment]
Je n'arrive pas à poster de capture d'écran mais c'est exactement ça, sur l'icône et le widget

**Comment by pmspr4100** [comment]
Ok merci pour la capture.
Le problème ne vient pas de la traduction mais d'un problème d'image.
Je vais voir avec Xiaomi.eu pour intégrée la traduction d'image.

**Comment by Micdu70** [comment]
@pmspr4100 Le problème vient surement de la traduction : Tu as déplacé le dossier "extras" ( pour quelle raison ? ) alors que les autres repos de traductions ne l'ont pas fait.

Je mets le repo pour la traduction Allemande comme exemple => https://github.com/berlinux2016/MIUI12/tree/master/German/extras

**Comment by pmspr4100** [comment]
Concernant le extras c'est plus une obligation car les values-fr sont intégrées de base.
Pour le problème cela provient des dossiers images de chaque application il y a les values-fr ect.... pour la langue et les dossiers drawable-hdpi, drawable-mdpi, drawable-xhdpi ect.... qui regroupe les images de l'application en question.
Donc crée les dossiers pour le fr et modifiée uniquement les images ou icônes

**Comment by jblum66** [comment]
Ces images sont-elles dans la partition dynamique super.img ? Quel outil utiliser dans Windows pour extraire la partition super et la convertir en partitions ext4 ?

**Comment by jblum66** [comment]
Je ne trouve pas d'images correspondantes dans l'APK de DeskClock

**Comment by pmspr4100** [comment]
> Je ne trouve pas d'images correspondantes dans l'APK de DeskClock ou Calendar.

APK version décompiler et non ouvert comme un fichier zip ect...

**Comment by pmspr4100** [comment]
> Je ne trouve pas d'images correspondantes dans l'APK de DeskClock ou Calendar.

Il faut décompiler l'application pour voir les fichiers voila j'ai récupérer une version du calendrier et voila l'exemple d'un dossier qu'il faut faire.
drawable-fr-rFR-xxhdpi
![widget_agenda_icon](https://user-images.githubusercontent.com/49132275/142698688-3c220d61-e2fe-4114-803d-dc04c2a4a6f5.png)
![widget_agenda_preview](https://user-images.githubusercontent.com/49132275/142698689-121ffbcc-6c89-47c4-bd33-34717488dfd1.png)
![widget_month_icon](https://user-images.githubusercontent.com/49132275/142698691-7f141aab-3000-440c-b55c-064ccd959990.png)
![widget_month_preview](https://user-images.githubusercontent.com/49132275/142698693-da4bf1cb-ac0d-44f7-b75f-5d952d5fa661.png)
i

**Comment by jblum66** [comment]
J'avais bien trouvé ces images aussi. Mais je ne trouve pas celles utilisées pour afficher les jours en anglais dans l'icône de l'application, et qu'il faudrait mettre en français.

**Comment by pmspr4100** [comment]
Liste des apks 👍 les framworks miui.apk MiuiSystem.apk System.apk

**Comment by jblum66** [comment]
Ok je vais décompresser tout ça pour voir.

**Comment by jblum66** [comment]
Je n'ai rien trouvé de probant. Vu qu'il s'agit d'une icône adaptative, j'espère qu'ils ne génèrent pas l'image dynamiquement en appelant une police de caractères et en faisant un export png ou webm pour fabriquer une icône.

**Comment by pmspr4100** [comment]
Ok une fois la rom décompiler regarde dans le ZIP ça doit être liée a un pack d'icônes que xiaomi.eu intègre

**Comment by mimik0** [comment]
Juste pour info, Dimanche est bien en français.

**Comment by thebestuserdata** [comment]
Hello, j'ai le même souci sur mon mix 4, dernière mise à jour hier pour info.

![IMG_20211124_131933](https://user-images.githubusercontent.com/37451876/143237318-bf6863d5-9580-46bd-839a-00237ca459c1.jpg)

**Comment by jblum66** [comment]
Je vais refaire une passe complète sur les fichiers car j'ai 65 fichiers contenant le libellé "monday" dans les applis en français, contre 74 dans les applis en anglais/chinois. J'espère que ça donnera quelque chose, car je n'ai rien trouvé comme image dans les ressources des APK.

**Comment by jblum66** [comment]
Pas sûr à 100%, mais je crois que le problème venait de MiuiHome.apk. Le libellé "dimanche" était présent mais pas les autres.
À confirmer lors d'une prochaine release...

**Comment by pmspr4100** [comment]
Correction OK normalement
