### ISSUE TITLE
Nouvelle traduction 21.10.20/22

### ISSUE THREAD

**Issue by MassimoBF** [pmspr4100/MA-XML-12-FRENCH#185]
- **Version MIUI:** 21.10.20/22
- **Nom de l'appareil:** Mi 11

Bonjour avec la mise à jour il y a la nouvelle partie 
"Safety & Emergency " qui doit être traduite.

Merci 

![Screenshot_2021-10-27-21-00-58-218_com android settings](https://user-images.githubusercontent.com/81257813/139130999-58e88fd4-d559-4cc6-b83a-99e073aed365.jpg)

![Screenshot_2021-10-27-21-01-02-975_com android settings](https://user-images.githubusercontent.com/81257813/139131015-23cf2386-33f9-41b6-9d02-881e9d7925cd.jpg)

**Comment by jblum66** [comment]
@MassimoBF pourras-tu tester sur la dernière version de la ROM stp ?

**Comment by MassimoBF** [comment]
> @MassimoBF pourras-tu tester sur la dernière version de la ROM stp ?

Tout est parfait. Merci
