### ISSUE TITLE
Mise en garde passage en mode performance

### ISSUE THREAD

**Issue by mimik0** [pmspr4100/MA-XML-12-FRENCH#186]
- Version MIUI: 12.5.15 Stable
- Nom de l'appareil: Mi 11

![IMG_20211109_233034.jpg](https://user-images.githubusercontent.com/59457838/141016261-147ce6bd-13cd-4207-bb69-7f487a86289e.jpg)

**Comment by jblum66** [comment]
Bonjour, il s'agit en effet d'un libellé manquant. Je vais l'ajouter.
Merci pour ce signalement.

**Comment by mimik0** [comment]
Je vous en pris si ça peut aider
