### ISSUE TITLE
Quelques erreurs de traduction

### ISSUE THREAD

**Issue by s1w2a3** [pmspr4100/MA-XML-12-FRENCH#25]
- **Version MIUI:** MIUI 12.0.3
- **Nom de l'appareil:** Mi 9 (Cepheus)

**Capture d'écran/Description:**
Bonjour,
Tout d'abord, merci pour ce travail de traduction. Afin d'améliorer sa qualité, je liste ci-dessous quelques erreurs de traduction (le plus souvent des erreurs d'orthographe) :
- Dans le centre de contrôle (à activer dans les paramètres),  au-dessus de la consommation de données mobiles, il est écrit : "utilisées ce mois", alors que la consommation est exprimée en octets ou ses multiples qui sont tous masculins. Il faudrait donc écrire "utilisés ce mois" ou "utilisés ce mois-ci" où encore "consommation de données mobiles".
- Toujours dans le centre de contrôle, en-dessous des données cellulaires il est écrit "activé" au lieu de "activées".
![Screenshot_2020-07-25-13-13-41-549_com google android apps photos](https://user-images.githubusercontent.com/68775901/88456238-642a9400-ce7c-11ea-99ca-0a45c675ac82.jpg)

- Dans le centre de contrôle (à nouveau) la lampe torche s'appelle "Flash" et le mode silencieux s'appelle "Silence".
- Lorsqu'on modifie les tuiles du centre de contrôle (icône en haut à droite), il est écrit "Ajoutés raccourcis" au lieu de "Ajouter des raccourcis".
![Screenshot_2020-07-25-13-16-34-938_com brave browser](https://user-images.githubusercontent.com/68775901/88455831-16605c80-ce79-11ea-95c5-32ce0da089ff.jpg)
- Dans les paramètres "Affichage permanent et écran de verrouillage", l'"Affichage permanent" s'appelle en fait "Affichage ambiant". Choisir un seul nom pour cette option serait mieux (je pense d'ailleurs que le terme anglais "Always on display" serait plus clair).
- Toujours dans les paramètres "Affichage permanent et écran de verrouillage", la phrase "Quand les notifications arrivent et que l'écran est..." est trop longue et ne s'affiche pas entièrement (impossible de passer en mode paysage dans ces paramètres). Il vaudrait mieux écrire "Notifications pendant Always on display" (si ce nom est retenu). De plus, à droite de cette phrase, il est écrit "Ne fais rien", ce qui contient une erreur de conjugaison. Il vaudrait mieux mettre "Ne rien faire".
![Screenshot_2020-07-25-13-27-01-187_com android settings](https://user-images.githubusercontent.com/68775901/88456004-87ecda80-ce7a-11ea-8a1b-87264a7b063d.jpg)
- Dans l'appareil photo, le mode "Time lapse" est traduit par "Laps de temps". Garder "Time lapse" ou mettre "Accéléré" serait plus clair.
![Screenshot_2020-07-25-13-28-34-130_com android camera](https://user-images.githubusercontent.com/68775901/88456090-29742c00-ce7b-11ea-9124-982d517a091b.jpg)
- Le mode "Économiseur de batterie ultra" s'appelle parfois "Ultra économiseur de batterie".
![Screenshot_2020-07-25-13-31-24-379_com miui securitycenter](https://user-images.githubusercontent.com/68775901/88456104-4e689f00-ce7b-11ea-8da7-baeb7b4651b0.jpg)
![Screenshot_2020-07-25-13-31-13-482_com miui securitycenter](https://user-images.githubusercontent.com/68775901/88456111-59233400-ce7b-11ea-8544-7b203eb1720a.jpg)
- Lorsque le bluetooth est en cours d'activation dans le centre de contrôle, il est écrit "Activer..." au lieu de "Activation...".
![Screenshot_2020-07-25-13-44-35-857_au com shiftyjelly pocketcasts](https://user-images.githubusercontent.com/68775901/88456360-62150500-ce7d-11ea-9c88-481dfb50d2cf.jpg)

Bonne journée !

**Comment by pmspr4100** [comment]
OK.
Par contre pour les activer, activée etc... à voir sur les prochaines version pour avoir un aperçu
