### ISSUE TITLE
Nouveaux issues de traduction

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-12-FRENCH#26]
-  Version MIUI:  20.7.23
-  Nom de l'appareil:  Mi CC9

Salut , j'ai trouver quelque erreurs de traduction Dans le chemin :

-  Application GALLERY - Souvenirs

![Screenshot_2020-07-26-01-39-06-488_com miui gallery](https://user-images.githubusercontent.com/60173587/88469051-5b6da880-cee4-11ea-90d7-8e68cdee8447.jpg)

-  Application GALLERY - Albums - Toutes les photos - 3 points

![Screenshot_2020-07-26-01-42-12-214_com miui gallery](https://user-images.githubusercontent.com/60173587/88469079-ae476000-cee4-11ea-8fd6-f984c39dba1f.jpg)

-  Application GALLERY - Albums - Toutes les photos - 3 points - Sort

![Screenshot_2020-07-26-01-42-18-872_com miui gallery](https://user-images.githubusercontent.com/60173587/88469085-e9499380-cee4-11ea-94e3-2a4467b8f257.jpg)

-  Paramètres - Affichage permanent et écran de verrouillage - Animation de charge  

![Screenshot_2020-07-26-01-43-07-361_com android settings](https://user-images.githubusercontent.com/60173587/88469098-244bc700-cee5-11ea-899a-b30ad70f8f38.jpg)
 

-  Paramètres - Bien-être numérique 

![Screenshot_2020-07-26-02-11-34-731_com xiaomi misettings](https://user-images.githubusercontent.com/60173587/88469124-8e646c00-cee5-11ea-961b-0a854eabfdac.jpg)

- Paramètres - Paramètre additionnels - boutons de raccourci - Capture d’écran partielle  

![Screenshot_2020-07-26-02-17-07-397_com android settings](https://user-images.githubusercontent.com/60173587/88469182-5b6ea800-cee6-11ea-9d31-012318ba5e43.jpg)

**Comment by pmspr4100** [comment]
OK
