### ISSUE TITLE
Petit oubli

### ISSUE THREAD

**Issue by s1w2a3** [pmspr4100/MA-XML-12-FRENCH#27]
- **Version MIUI:** 12.0.3
- **Nom de l'appareil:** Mi 9

**Capture d'écran/Description:**
Bonjour,
Voici une traduction manquante dans l'application horloge. Il suffit de lancer un chronomètre et de mettre un repère. En dessous du temps écoulé depuis le lancement du minuteur, il est écrit "Current timing".
![Screenshot_2020-07-28-14-44-33-744_com android deskclock](https://user-images.githubusercontent.com/68775901/88667355-8e30c000-d0e1-11ea-972c-399d7ffa27ae.jpg)

Dans les paramètres Bluetooth, "APPAREILS DISPONIBLES" est écrit en majuscules.
Bonne journée.

**Comment by jblum66** [comment]
Pour le chronomètre, la chaîne "current_stopwatch_time" n'est pas présente dans le répertoire "French". Il faudrait l'y ajouter @pmspr4100 

Pour les paramètres Bluetooth, je ne trouve pas cette chaîne "APPAREILS DISPONIBLES" en majuscules. Il est possible que ce soit MIUI qui la mette en majuscules.

**Comment by pmspr4100** [comment]
> Pour le chronomètre, la chaîne "current_stopwatch_time" n'est pas présente dans le répertoire "French". Il faudrait l'y ajouter @pmspr4100
> 
> Pour les paramètres Bluetooth, je ne trouve pas cette chaîne "APPAREILS DISPONIBLES" en majuscules. Il est possible que ce soit MIUI qui la mette en majuscules.

La ligne manquante intégré pour la traduction. Pour APPAREILS DISPONIBLES MIUI le bascule en majuscule.
