### ISSUE TITLE
Mi Mover

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-12-FRENCH#29]
-  Version MIUI: 20.7.23
-  Nom de l'appareil: Mi CC9

Salut , j'ai trouver des erreurs de traduction Dans L'application Mi Mover :

![Screenshot_2020-07-30-05-03-45-747_com miui huanji](https://user-images.githubusercontent.com/60173587/88879798-15398180-d223-11ea-8d2c-782bbb018b81.jpg)

**Comment by pmspr4100** [comment]
-Fixer
