### ISSUE TITLE
Erreur de traduction

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-12-FRENCH#30]
-  Version MIUI: 20.7.23
-  Nom de l'appareil: Mi CC9

Salut , j'ai trouver quelque erreurs de traduction dans le chemin :

-  Paramètre - mots de passe et sécurité - déverrouillage du visage

![Screenshot_2020-07-30-05-22-45-348_com android settings](https://user-images.githubusercontent.com/60173587/88880820-a6115c80-d225-11ea-8f61-4726197eac20.jpg)

**Comment by jblum66** [comment]
Libellés traduits
