### ISSUE TITLE
Traductions manquantes

### ISSUE THREAD

**Issue by s1w2a3** [pmspr4100/MA-XML-12-FRENCH#31]
- **Version MIUI:** 12.0.3
- **Nom de l'appareil:** Mi 9

**Capture d'écran/Description:**
Bonjour,
J'ai trouvé des traductions manquantes dans la section sommeil de l'application santé.
![Screenshot_2020-07-31-10-36-22-071_com mi health~3](https://user-images.githubusercontent.com/68775901/89018480-3e8a0880-d31c-11ea-9848-574dfc44128d.jpg)
![Screenshot_2020-07-31-10-36-11-431_com mi health~2](https://user-images.githubusercontent.com/68775901/89018482-3f229f00-d31c-11ea-9ade-3792fc9d8e5a.jpg)
![Screenshot_2020-07-31-10-36-09-007_com mi health~2](https://user-images.githubusercontent.com/68775901/89018483-3fbb3580-d31c-11ea-93b3-b87e1f70983a.jpg)
![Screenshot_2020-07-31-10-36-06-070_com mi health~2](https://user-images.githubusercontent.com/68775901/89018487-4053cc00-d31c-11ea-8c63-6e9f82c3ac76.jpg)
![Screenshot_2020-07-31-10-35-58-656_com mi health~2](https://user-images.githubusercontent.com/68775901/89018491-40ec6280-d31c-11ea-9035-115e10154f33.jpg)
![Screenshot_2020-07-31-10-36-03-188_com mi health~2](https://user-images.githubusercontent.com/68775901/89018492-4184f900-d31c-11ea-8315-af5169b80ce9.jpg)
De plus, dans les paramètres de permissions des applications, on peut régler une permission sur "tout en utilisant l'application", ce qui signifie en fait "lors de l'utilisation".
![Screenshot_2020-07-31-10-53-03-689_com miui securitycenter~2](https://user-images.githubusercontent.com/68775901/89018682-83ae3a80-d31c-11ea-8d07-671048d1ca23.jpg)
Bonne journée.

**Comment by jblum66** [comment]
Libellés traduits.
Le libellé "Tout en utilisant l'application" est utilisé un peu partout. On pourrait mettre "Lors de l'utilisation de l'application uniquement" mais cela serait trop long pour tenir sur une ligne.
