### ISSUE TITLE
Bluetooth/Haut parleur et Oreillette

### ISSUE THREAD

**Issue by dcarb** [pmspr4100/MA-XML-12-FRENCH#33]
- **Version MIUI:** 12.1
- **Nom de l'appareil:** k30 PRO

**Capture d'écran/Description:**
Lorsqu'on passe un appel et qu'on a une oreillette BT, on a le choix entre "Bluetooth/Haut parleur et Oreillette".
Mais oreillette est faux, c'est Oreille ou combiné.
Merci pour les traductions
Cordialement
Dominique

**Comment by pmspr4100** [comment]
Corrigé
