### ISSUE TITLE
Erreur de traduction en français

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-12-FRENCH#82]
Version MIUI: 21.2.3
Nom de l'appareil: Mi CC9
Salut , j'ai trouver quelque erreurs de traduction dans les chemin :

- Paramètre - connexion et partage - Mi share

![Screenshot_2021-02-05-02-07-58-961_com miui mishare connectivity](https://user-images.githubusercontent.com/60173587/106975923-c29fcb80-6757-11eb-9d61-5ba0e600df8f.jpg)

![Screenshot_2021-02-05-02-08-03-187_com miui mishare connectivity](https://user-images.githubusercontent.com/60173587/106975938-c92e4300-6757-11eb-8a3e-d244e353c889.jpg)

- Paramètre - connexion et partage - diffusion

![Screenshot_2021-02-05-02-15-58-599_com milink service](https://user-images.githubusercontent.com/60173587/106976388-96387f00-6758-11eb-8e20-d26fa91aaa63.jpg)

![Screenshot_2021-02-05-02-16-02-646_com milink service](https://user-images.githubusercontent.com/60173587/106976404-9b95c980-6758-11eb-8474-88a82341043b.jpg)

- Paramètre - connexion et partage - Configurer le point d’accès

![Screenshot_2021-02-05-02-21-18-033_com android settings](https://user-images.githubusercontent.com/60173587/106976755-44dcbf80-6759-11eb-96cc-68aa22319c67.jpg)

- Paramètre - affichage ambiant et écran de verrouillage - affichage ambiant

![Screenshot_2021-02-05-02-26-19-788_com android settings](https://user-images.githubusercontent.com/60173587/106977236-38a53200-675a-11eb-8cf9-b22a58cd3c3f.jpg)

![Screenshot_2021-02-05-02-26-31-367_com miui aod](https://user-images.githubusercontent.com/60173587/106977260-422e9a00-675a-11eb-8b09-8c90b0fd032e.jpg)

![Screenshot_2021-02-05-02-26-44-198_com miui aod](https://user-images.githubusercontent.com/60173587/106977270-4955a800-675a-11eb-841c-86777d892a75.jpg)

- Paramètre - Affichage

![Screenshot_2021-02-05-02-32-58-621_com android settings](https://user-images.githubusercontent.com/60173587/106977641-034d1400-675b-11eb-84a1-db822d95392a.jpg)

![Screenshot_2021-02-05-02-33-17-812_com android settings](https://user-images.githubusercontent.com/60173587/106977655-06e09b00-675b-11eb-8bb6-a174e53c06e0.jpg)

![Screenshot_2021-02-05-02-33-43-287_com android settings](https://user-images.githubusercontent.com/60173587/106977661-0a742200-675b-11eb-933c-2887a643cac7.jpg)

 - Paramètre - Sonnerie

![Screenshot_2021-02-05-02-38-33-340_com android settings](https://user-images.githubusercontent.com/60173587/106977993-a56cfc00-675b-11eb-89f6-b02ed1eb1b6d.jpg)

- Paramètre - Sonnerie - Assistant son

![Screenshot_2021-02-05-02-37-38-443_com miui misound](https://user-images.githubusercontent.com/60173587/106978027-b74e9f00-675b-11eb-8c77-a4d051ae3cf3.jpg)

- Paramètre - écran d'accueil

![Screenshot_2021-02-05-02-42-55-401_com miui home](https://user-images.githubusercontent.com/60173587/106978251-304df680-675c-11eb-9637-639f8560ae1a.jpg)

- Paramètre - écran d'accueil - Flouter les aperçaus d'applications

![Screenshot_2021-02-05-02-43-12-317_com miui securitycenter](https://user-images.githubusercontent.com/60173587/106978313-51aee280-675c-11eb-8c7f-3673cda6c408.jpg)

- Paramètre - Gestion des applications - applications clonées 

![Screenshot_2021-02-05-02-48-26-525_com miui securitycore](https://user-images.githubusercontent.com/60173587/106978649-f0d3da00-675c-11eb-9c01-7533461430bb.jpg)

- Paramètre - Paramètres additionnels - accessibilité - Physique - temps d'interaction 

![Screenshot_2021-02-05-02-52-57-643_com android settings](https://user-images.githubusercontent.com/60173587/106978931-8d967780-675d-11eb-860c-575e5eb9c3bd.jpg)

- Paramètre - Paramètres additionnels - options pour les développeurs

![Screenshot_2021-02-05-02-56-55-341_com android settings](https://user-images.githubusercontent.com/60173587/106979427-92a7f680-675e-11eb-90a1-73766af28945.jpg)

![Screenshot_2021-02-05-02-57-09-995_com android settings](https://user-images.githubusercontent.com/60173587/106979433-950a5080-675e-11eb-8c3d-44cac60e7e87.jpg)

![Screenshot_2021-02-05-02-57-25-819_com android settings](https://user-images.githubusercontent.com/60173587/106979439-976caa80-675e-11eb-980f-c0364b9d705b.jpg)

![Screenshot_2021-02-05-02-57-50-782_com android settings](https://user-images.githubusercontent.com/60173587/106979445-9a679b00-675e-11eb-8b4d-e176323ed3a6.jpg)

![Screenshot_2021-02-05-02-58-01-319_com android settings](https://user-images.githubusercontent.com/60173587/106979450-9dfb2200-675e-11eb-8c8f-17265269545e.jpg)

![Screenshot_2021-02-05-02-56-25-280_com android settings](https://user-images.githubusercontent.com/60173587/106979413-8e7bd900-675e-11eb-82e3-36f94a0d67e5.jpg)

![Screenshot_2021-02-05-02-56-36-213_com android settings](https://user-images.githubusercontent.com/60173587/106979422-90de3300-675e-11eb-9f90-78df32fd3684.jpg)

**Comment by jblum66** [comment]
Merci pour le signalement.
Pas mal de corrections dans le pull request #85 
Il faudra vérifier si tu utilises bien la dernière version de Xiaomi.eu car certains libellés semblent déjà traduits pour moi.

**Comment by bigjackwww** [comment]
Oui, je suis déjà dans la dernière version de xiaomi.eu
![Screenshot_2021-02-05-19-01-34-172_com android updater](https://user-images.githubusercontent.com/60173587/107071229-b3b32a80-67e4-11eb-8a94-84bb583df24c.jpg)

**Comment by jblum66** [comment]
Il reste encore des libellés en anglais. Certains semblent pourtant traduits; je pense qu'ils ne sont pas pris en compte.
Il y a aussi un libellé "always_style_s**y**mmary" mal écrit en anglais dans MiuiAod.apk, ce qui pourrait expliquer pourquoi la traduction française ne s'affiche pas. J'ai dupliqué la ligne en corrigeant le libellé en "always_style_s**u**mmary" pour voir s'il s'affichera en français.
