### ISSUE TITLE
Application Galerie

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-12-FRENCH#86]
Version MIUI: 21.2.3
Nom de l'appareil: Mi CC9
Salut , j'ai trouver quelque erreurs de traduction dans application Galerie  :

App Galerie - 3 dots - Paramètres - Corbeille

![IMG_20210214_021207](https://user-images.githubusercontent.com/60173587/107866177-0e482880-6e6e-11eb-9fd7-1ac9be1e2cc8.jpg)

App Galerie - Choisissez n'importe quelle image - Plus

![Screenshot_2021-02-14-02-34-19-267_com miui gallery](https://user-images.githubusercontent.com/60173587/107866189-333c9b80-6e6e-11eb-886c-c60d2b45751e.jpg)

**Comment by jblum66** [comment]
Corrigé dans #98

**Comment by Micdu70** [comment]
On peut close l'issue. ;)
