### ISSUE TITLE
Quelque erreurs de traduction

### ISSUE THREAD

**Issue by bigjackwww** [pmspr4100/MA-XML-12-FRENCH#9]
-  Version MIUI:   20.5.21 (Beta) 
-  Nom de l'appareil:  Mi CC9

Salut , j'ai trouver un erreur de traduction Dans le chemin : 

- Paramètres - Affichage permanent et écran de verrouillage - sélectionnez le format de l’horloge - informations du propriétaire sur l"écran de verrouillage

![Screenshot_2020-05-24-06-58-51-384_com android systemui](https://user-images.githubusercontent.com/60173587/82746890-8163b900-9d8c-11ea-91fb-437737140c8b.jpg)

- Paramètres - Affichage permanent et écran de verrouillage - fond d’écran  carrousel - articles bloqués

![Screenshot_2020-05-24-07-03-14-760_com mfashiongallery emag](https://user-images.githubusercontent.com/60173587/82746938-eae3c780-9d8c-11ea-8a5b-68f71f2e6a4a.jpg)

 
- Paramètres - Thèmes

![Screenshot_2020-05-24-07-07-51-775_com android thememanager](https://user-images.githubusercontent.com/60173587/82747044-85440b00-9d8d-11ea-8225-4948af2b7762.jpg)
 

- App Camera - Paramètres 

![Screenshot_2020-05-24-07-13-32-119_com android camera](https://user-images.githubusercontent.com/60173587/82747162-6b56f800-9d8e-11ea-8ab5-9875ad846353.jpg)

- App Camera - Paramètres - customize

![Screenshot_2020-05-24-07-14-57-199_com android camera](https://user-images.githubusercontent.com/60173587/82747227-d3a5d980-9d8e-11ea-85f4-1e5a1d1d9d83.jpg)
![Screenshot_2020-05-24-07-15-03-957_com android camera](https://user-images.githubusercontent.com/60173587/82747228-d4d70680-9d8e-11ea-93a3-9f6cb7f205b2.jpg)
![Screenshot_2020-05-24-07-15-10-533_com android camera](https://user-images.githubusercontent.com/60173587/82747229-d56f9d00-9d8e-11ea-8a1f-3b4f23e8beb5.jpg)
![Screenshot_2020-05-24-07-15-17-752_com android camera](https://user-images.githubusercontent.com/60173587/82747230-d6083380-9d8e-11ea-9875-cb42f1746e9a.jpg)
![Screenshot_2020-05-24-07-15-24-518_com android camera](https://user-images.githubusercontent.com/60173587/82747231-d6083380-9d8e-11ea-9701-e82f72a2a60c.jpg)

**Comment by Micdu70** [comment]
Ce ne sont pas des "erreurs de traduction" mais que ça n'a pas été encore traduit en FR. ;)

**Comment by pmspr4100** [comment]
-Terminé pour la prochaine version

**Comment by bigjackwww** [comment]
Merci beaucoup
